# This file is not "true" dataset_params file, but rather a collection of settings that describe
# skeleton configuration specific to COCO dataset. It is used by other dataset_params files to
# avoid code duplication.

num_joints: 565
oks_sigma:  0.025

