defaults:
  - training_hyperparams: vgg_head_train_params
  - dataset_params: vgg_head_small_medium_albu_augs
  - arch_params: segformer_b5_yolo
  - checkpoint_params: default_checkpoint_params
  - _self_
  - variable_setup

architecture: SegFormerYoloHeads

multi_gpu: Off
num_gpus: 1

experiment_suffix: ""
experiment_name: ${hydra:runtime.choices.arch_params}_${hydra:runtime.choices.dataset_params}_${hydra:runtime.choices.training_hyperparams}_${experiment_suffix}

checkpoint_params:
  checkpoint_path: https://sghub.deci.ai/models/segformer_b5_cityscapes.pth
  strict_load:
    _target_: super_gradients.training.sg_trainer.StrictLoad
    value: key_matching

dataset_params:
  train_dataset_params:
    data_dir: g:\VGGHead\okupyn-20240506-VGGHead\VGGHead\small

  val_dataset_params:
    data_dir: g:\VGGHead\okupyn-20240506-VGGHead\VGGHead\small

  train_dataloader_params:
    persistent_workers: True
    batch_size: 4

  val_dataloader_params:
    persistent_workers: True
    batch_size: 4


hydra:
  searchpath:
    - configs
    - pkg://super_gradients.recipes
