defaults:
  - training_hyperparams: vgg_head_train_params
  - dataset_params: vgg_head_large
  - arch_params: yolo_heads_l_arch_params
  - checkpoint_params: default_checkpoint_params
  - _self_
  - variable_setup

architecture: YoloHeads

multi_gpu: Off
num_gpus: 1

experiment_suffix: ""
experiment_name: ${hydra:runtime.choices.arch_params}_${hydra:runtime.choices.dataset_params}_${hydra:runtime.choices.training_hyperparams}_${experiment_suffix}

training_hyperparams:
  ema: True
  visualization_frequency_epochs: 1
  max_epochs: 50
  mixed_precision: False
  initial_lr: 5e-5

checkpoint_params:
  # For training Yolo-NAS-S pose estimation model we use pretrained weights for Yolo-NAS-S object detection model.
  # By setting strict_load: key_matching we load only those weights that match the keys of the model.
  checkpoint_path: https://sghub.deci.ai/models/yolo_nas_l_coco.pth
  strict_load:
    _target_: super_gradients.training.sg_trainer.StrictLoad
    value: key_matching

dataset_params:
  train_dataset_params:
    data_dir: g:\VGGHead\okupyn-20240506-VGGHead\VGGHead\large

  val_dataset_params:
    data_dir: g:\VGGHead\okupyn-20240506-VGGHead\VGGHead\large

  train_dataloader_params:
    persistent_workers: True
    batch_size: 4
    num_workers: 16

  val_dataloader_params:
    persistent_workers: True
    batch_size: 4


hydra:
  searchpath:
    - configs
    - pkg://super_gradients.recipes
