defaults:
  - training_hyperparams: vgg_head_train_params
  - dataset_params: vgg_head
  - arch_params: yolo_nas_pose_m_arch_params
  - checkpoint_params: default_checkpoint_params
  - _self_
  - variable_setup

architecture: yolo_nas_pose_m

multi_gpu: Off
num_gpus: 1

experiment_suffix: ""
experiment_name: vgg_head_${architecture}_${experiment_suffix}_${dataset_params.dataset_params_suffix}

arch_params:
  num_classes: ${dataset_params.num_joints}

training_hyperparams:
  initial_lr:  1e-4 # Scale factor to account reduced batch size

  criterion_params:
    dfl_loss_weight: 0.5
    pose_reg_loss_weight: 10

  ema_params:
    decay_type: exp
    beta: 50

checkpoint_params:
  # For training Yolo-NAS-S pose estimation model we use pretrained weights for Yolo-NAS-S object detection model.
  # By setting strict_load: key_matching we load only those weights that match the keys of the model.
  checkpoint_path: https://sghub.deci.ai/models/yolo_nas_m_coco.pth
  strict_load:
    _target_: super_gradients.training.sg_trainer.StrictLoad
    value: key_matching

dataset_params:
  train_dataloader_params:
    batch_size: 20
    persistent_workers: True

  val_dataloader_params:
    batch_size: 20
    persistent_workers: True


hydra:
  searchpath:
    - configs
    - pkg://super_gradients.recipes
